### ISSUE TITLE
[BUG] LM35 e Potenciômetro no projeto PID

### ISSUE THREAD

**Issue by VictorBrugnago** [DA0HN/microcontroladores#3]
**Descreva o bug**
O projeto de PID não está funcionando corretamente, o potenciômetro e o LM25 não são ativados no simulador

**Comment by da0hn** [comment]
[projeto-pid.zip](https://github.com/da0hn/microcontroladores/files/7657084/projeto-pid.zip)

Versão do CCS utilizada: v5.025

Solved

**Comment by VictorBrugnago** [comment]
Foi mal, era a versão do meu CCS, estava a utilizar a versão 5.007. Por favor, inclua uma nota informando que é necessário a versão 5.025 ou superior.
